#!/usr/bin/env python
import rospy
from robotiq_3f_gripper_articulated_msgs.msg import Robotiq3FGripperRobotOutput

def closing_callback(event):
    print "Published and latched Close Gripper message for 3.0 seconds"
    rospy.signal_shutdown("Stop publishing")

def close_gripper():
    pub = rospy.Publisher('/left_hand/command', Robotiq3FGripperRobotOutput, queue_size=1)
    rospy.init_node('close_gripper')
    close_command = Robotiq3FGripperRobotOutput()
    close_command.rACT = 1
    close_command.rGTO = 1
    close_command.rPRA = 250 
    close_command.rSPA = 200 
    close_command.rFRA = 200 
    rate = rospy.Rate(10) 
    rospy.Timer(rospy.Duration(3.0), closing_callback)
    while not rospy.is_shutdown():
           pub.publish(close_command)   
           rate.sleep()
        

if __name__ == '__main__': 
    try:
        close_gripper()
    except rospy.ROSInterruptException:
        pass
